package telas;

import ConexaoBD.BD;
import ConexaoBD.mostraTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class cadastro extends javax.swing.JFrame {

    BD conexao = new BD();

    public cadastro() {
        initComponents();
        conexao.conecta();
        preencherTabela("SELECT * FROM clientes ORDER by codCliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobotao = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        telefone3 = new javax.swing.JTextField();
        tituloCadastro = new javax.swing.JLabel();
        msgNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        msgEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        msgCpf = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        msgSexo = new javax.swing.JLabel();
        feminino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        btnProcurar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        msgTelefone = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        municipio = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        btnApagar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tituloCadastro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloCadastro.setForeground(new java.awt.Color(219, 147, 41));
        tituloCadastro.setText("CADASTRO");
        getContentPane().add(tituloCadastro);
        tituloCadastro.setBounds(230, 0, 110, 30);

        msgNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgNome.setForeground(new java.awt.Color(255, 255, 255));
        msgNome.setText("Nome: ");
        getContentPane().add(msgNome);
        msgNome.setBounds(90, 60, 70, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 90, 350, 2);

        msgEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgEmail.setForeground(new java.awt.Color(255, 255, 255));
        msgEmail.setText("E-mail:");
        getContentPane().add(msgEmail);
        msgEmail.setBounds(90, 110, 70, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(90, 150, 350, 2);

        msgCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgCpf.setForeground(new java.awt.Color(255, 255, 255));
        msgCpf.setText("CPF:");
        getContentPane().add(msgCpf);
        msgCpf.setBounds(90, 160, 60, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(90, 200, 350, 10);

        msgSexo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgSexo.setForeground(new java.awt.Color(255, 255, 255));
        msgSexo.setText("Sexo:");
        getContentPane().add(msgSexo);
        msgSexo.setBounds(90, 250, 60, 20);

        grupobotao.add(feminino);
        feminino.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        feminino.setForeground(new java.awt.Color(255, 255, 255));
        feminino.setText("Feminino");
        feminino.setOpaque(false);
        getContentPane().add(feminino);
        feminino.setBounds(350, 250, 90, 25);

        grupobotao.add(masculino);
        masculino.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        masculino.setForeground(new java.awt.Color(255, 255, 255));
        masculino.setText("Masculino");
        masculino.setOpaque(false);
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });
        getContentPane().add(masculino);
        masculino.setBounds(170, 250, 100, 25);

        btnProcurar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 147, 41), 1, true));
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(90, 300, 110, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(90, 244, 350, 10);

        msgTelefone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgTelefone.setForeground(new java.awt.Color(255, 255, 255));
        msgTelefone.setText("Mun");
        getContentPane().add(msgTelefone);
        msgTelefone.setBounds(90, 200, 90, 40);
        getContentPane().add(nome);
        nome.setBounds(170, 50, 270, 30);
        getContentPane().add(municipio);
        municipio.setBounds(170, 210, 270, 30);

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf);
        cpf.setBounds(170, 160, 270, 30);
        getContentPane().add(email);
        email.setBounds(170, 110, 270, 30);

        btnApagar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnApagar1.setText("Apagar");
        btnApagar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 147, 41), 1, true));
        btnApagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar1);
        btnApagar1.setBounds(210, 300, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 300, 110, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundEdit2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -80, 610, 470);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 342, 540, 420);

        setSize(new java.awt.Dimension(596, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        procurar procurar = new procurar ();
                 procurar.setVisible(true);
                 dispose ();
        
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnApagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApagar1ActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        // TODO add your handling code here:
        


    }//GEN-LAST:event_masculinoActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         conexao.conecta();
        try {
            PreparedStatement pst = conexao.conex.prepareStatement("INSERT INTO clientes (nome,email,cpf,municipio) VALUES (?,?,?,?)");
            pst.setString(1, nome.getText());
            pst.setString(2, email.getText());
            pst.setString(3, cpf.getText());
            pst.setString(4, municipio.getText());
           /* pst.setString(5, masculino.getText());
            pst.setString(5, feminino.getText());*/
        
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            nome.setText("");
            email.setText("");
            cpf.setText("");
            municipio.setText("");
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro! Cadastro não efetuado" + ex.toString());
        }
        conexao.desconecta();
    }//GEN-LAST:event_jButton1ActionPerformed

   public void preencherTabela(String Sql){
       ArrayList dados = new ArrayList ();
       String [] colunas = new String[] {"nome", "email", "cpf"};
       conexao.conecta();
       conexao.executaSQL (Sql);
       
       try {
           conexao.rs.first();
           do{
               dados.add(new Object [] {conexao.rs.getString("nome"), conexao.rs.getString ("email"),
               conexao.rs.getString("cpf")});
               
           }while (conexao.rs.next());
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ARRAYLIST"+ex);
       }
       mostraTabela tabela = new mostraTabela (dados, colunas);
       jTable1.setModel(tabela);
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);       
       jTable1.getColumnModel().getColumn(0).setResizable(false);
       jTable1.getColumnModel().getColumn(1).setPreferredWidth(200); 
       jTable1.getColumnModel().getColumn(1).setResizable(false);       
       jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);       
       jTable1.getColumnModel().getColumn(2).setResizable(false);
       jTable1.getTableHeader().setReorderingAllowed(false);
       jTable1.setAutoResizeMode (jTable1.AUTO_RESIZE_OFF);
       jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       conexao.desconecta();
               
       
       
       
   }
   
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnApagar1;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton feminino;
    private javax.swing.ButtonGroup grupobotao;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JLabel msgCpf;
    private javax.swing.JLabel msgEmail;
    private javax.swing.JLabel msgNome;
    private javax.swing.JLabel msgSexo;
    private javax.swing.JLabel msgTelefone;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField telefone3;
    private javax.swing.JLabel tituloCadastro;
    // End of variables declaration//GEN-END:variables
}
