/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import ConexaoBD.BD;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class procurar extends javax.swing.JFrame {
BD conexao = new BD();
    /**
     * Creates new form procurar
     */
    public procurar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLogin = new javax.swing.JLabel();
        msgId = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        procurarId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        msgMunicipio = new javax.swing.JLabel();
        municipio = new javax.swing.JTextField();
        msgNome1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        cpf = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        msgCpf = new javax.swing.JLabel();
        msgEmail = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tituloLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(219, 147, 41));
        tituloLogin.setText("Procurar:");
        getContentPane().add(tituloLogin);
        tituloLogin.setBounds(210, 0, 110, 30);

        msgId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgId.setForeground(new java.awt.Color(255, 255, 255));
        msgId.setText("ID:");
        getContentPane().add(msgId);
        msgId.setBounds(60, 40, 40, 30);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 147, 41), 1, true));
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(300, 300, 110, 30);
        getContentPane().add(procurarId);
        procurarId.setBounds(140, 40, 270, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 90, 490, 10);

        msgMunicipio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        msgMunicipio.setText("Municipio:");
        getContentPane().add(msgMunicipio);
        msgMunicipio.setBounds(50, 250, 100, 30);
        getContentPane().add(municipio);
        municipio.setBounds(160, 250, 270, 30);

        msgNome1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgNome1.setForeground(new java.awt.Color(255, 255, 255));
        msgNome1.setText("Nome: ");
        getContentPane().add(msgNome1);
        msgNome1.setBounds(50, 130, 70, 20);
        getContentPane().add(nome);
        nome.setBounds(160, 130, 270, 30);

        btnProcurar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 147, 41), 1, true));
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(430, 40, 110, 30);

        btnDeletar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDeletar.setText("Apagar");
        btnDeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 147, 41), 1, true));
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(140, 300, 110, 30);

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf);
        cpf.setBounds(160, 170, 270, 30);
        getContentPane().add(email);
        email.setBounds(160, 210, 270, 30);

        msgCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgCpf.setForeground(new java.awt.Color(255, 255, 255));
        msgCpf.setText("CPF:");
        getContentPane().add(msgCpf);
        msgCpf.setBounds(50, 170, 70, 30);

        msgEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgEmail.setForeground(new java.awt.Color(255, 255, 255));
        msgEmail.setText("Email:");
        getContentPane().add(msgEmail);
        msgEmail.setBounds(50, 210, 70, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundEdit2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 330);

        setSize(new java.awt.Dimension(596, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        conexao.conecta();
        try{
            PreparedStatement pst = conexao.conex.prepareStatement(" UPDATE clientes set nome=?, email=?, cpf=?, municipio=? where codCliente="+procurarId.getText());
            
            pst.setString (1, nome.getText());
            pst.setString (2, email.getText());           
            pst.setString (3, cpf.getText());
            pst.setString (4, municipio.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Editado com sucesso.");
            
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao editar"+ex.toString());
        
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        conexao.conecta();
        conexao.executaSQL("SELECT * FROM clientes WHERE codCliente="+procurarId.getText());
        try{
            conexao.rs.first();
            nome.setText(conexao.rs.getString("nome"));
            municipio.setText(conexao.rs.getString("cpf"));
            email.setText(conexao.rs.getString("email"));
            cpf.setText(conexao.rs.getString("cpf"));
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao localizar registro!");
            
        }
        btnEditar.setEnabled(true);
        btnDeletar.setEnabled(true);
        conexao.desconecta();
        
        
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
       int resposta = 0;
       resposta= JOptionPane.showConfirmDialog(rootPane,"Deseja remover o registro?");
       if (resposta == JOptionPane.YES_OPTION){
           conexao.conecta();
           try{
               PreparedStatement pst = conexao.conex.prepareStatement("Delete from clientes where codCliente=?");
               pst.setString(1, procurarId.getText());
               pst.execute();
               JOptionPane.showMessageDialog(null, "Registro excluido com sucesso!");               
           }catch(SQLException ex){
               JOptionPane.showMessageDialog(null,"Erro! Remoção de dados não efetuda."+ex.toString());                     
           }
           nome.setText("");
           municipio.setText("");
           email.setText("");
           cpf.setText("");
           
       }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new procurar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel msgCpf;
    private javax.swing.JLabel msgEmail;
    private javax.swing.JLabel msgId;
    private javax.swing.JLabel msgMunicipio;
    private javax.swing.JLabel msgNome1;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField procurarId;
    private javax.swing.JLabel tituloLogin;
    // End of variables declaration//GEN-END:variables
}
